const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const asar = require('@electron/asar');
const yaml = require('js-yaml');
const config = require('../electron-builder.prueba.cjs');
const output = path.resolve(__dirname, '../dist-prueba');
const metadata = yaml.load(fs.readFileSync(path.join(output, 'prueba.yml'), 'utf8'));
assert.equal(metadata.version, config.extraMetadata.version);
assert.equal(fs.existsSync(path.join(output, 'latest.yml')), false, 'Una prueba no debe generar latest.yml');
const installer = fs.readFileSync(path.join(output, metadata.path));
assert.equal(crypto.createHash('sha512').update(installer).digest('base64'), metadata.sha512);
const resources = path.join(output, 'win-unpacked/resources');
const pkg = JSON.parse(asar.extractFile(path.join(resources, 'app.asar'), 'package.json'));
assert.equal(pkg.name, 'hub-de-ingresos-prueba');
assert.equal(pkg.releaseChannel, 'prueba');
assert.equal(pkg.version, metadata.version);
const feed = yaml.load(fs.readFileSync(path.join(resources, 'app-update.yml'), 'utf8'));
assert.equal(feed.channel, 'prueba');
assert.equal(feed.releaseType, 'prerelease');
assert.equal(feed.repo, 'app-horas-laborales');
assert.equal(feed.owner, 'iatoby167');
assert.notEqual(feed.updaterCacheDirName, 'hub-de-ingresos-updater');
console.log(`OK: ${metadata.version}, instalador y canal de prueba aislados; SHA-512 verificado.`);
